version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  construct:
    cmds:
      - mkdir temp
      - echo 'Made a Directory!'
  destroy:
    cmds:
      - rm -d new_directory
      - echo 'Deleted a Directory!'
  commit:
    cmds:
      - git c -m new_commit
  all:
    cmds:
      - task construct
      - task destroy
      - task hello